version: '3'
services:
  couchbase:
    image: couchbase/server
    container_name: couchbase-server
    volumes:
      - /etc/cb/data:/opt/couchbase/var
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
  
  dcp-client:
    build: .
    image: dcp-client-example:test
    container_name: dcp-client-example
    links:
        - "couchbase:couchbase"
    environment:
      - CB_HOSTNAME=couchbase-server
      - BUCKET=travel-sample
      - CB_USER=Administrator
      - CB_PASSWORD=password
      - MINUTES_WAITING=30
      - IS_NOOP="false"
    depends_on:
      - couchbase
